include:
  - ./networks.yml

services:

  redis:
    container_name: redis
    platform: ${PLATFORM}
    image: redis:7.2.4-alpine
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - nuggets
      - nuggets-internal

volumes:
  redis_data:
